spring.application.name=sake

mysql.main.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.mysql.main.jdbc-url=jdbc:mysql://localhost:3306/sake_db?zeroDateTimeBehavior=convertToNull
mysql_main_jdbc-url=jdbc:log4jdbc:mysql://localhost:3306/sake_db?zeroDateTimeBehavior=convertToNull
mysql_main_username=root
mysql_main_password=~rladusdyd48756

# who: by 
google_mail_username =aa39421371@gmail.com
google_app_password=ltscvvjjmdiwbxyw


